config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following,:followers
    end
  end
  resources :answers,only:[:new,:create,:edit,:update]
  resources :account_activations,only:[:edit]
  resources :password_resets,only:[:new,:create,:edit,:update]
  resources :microposts,only:[:edit,:create,:destroy,:update,:show,:more] do
    member do
      get :more
    end
  end
  resources :relationships,only: [:create,:destroy]
  root 'static_pages#home'
  get 'home',            to:      'static_pages#home'
  get 'help'  ,            to:     'static_pages#help'
  get 'about'                =>      'static_pages#about'
  get 'contact'              =>     'static_pages#contact'
  get 'signup'               =>    'users#new'
  get 'login',                 to:    'sessions#new'
  post 'login',                 to:     'sessions#create'
  delete 'logout',                to:    'sessions#destroy'

end

app/views/shared/_answer_form.html.erb
<%= form_for(micropost.answers.build) do |f| %>
<%= render 'shared/error_messages',object:f.object  %>
<div class="answer-field">
  <%= f.text_area :response, placeholder: "Your response..." %>
  <%= f.hidden_field :micropost_id, value: micropost.id  %>
<section  class="post-button">
  <%= f.submit "Respond", class: "btn btn-primary" %>
</section>
</div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(object.errors.count, "error") %>.
  </div>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
  <%= render @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_following_list.html.erb
<div class="user_avatars">
  <ul class="follow-list">
    <% @users.each do |user| %>
    <li>
      <span>
        <%= link_to gravatar_for(user, size: 30), user %>
      </span>
      <span>
        <%= link_to user.name, user %>
      </span>
    </li>
    <% end %>
  </ul>
</div>

app/views/shared/_micropost_content.html.erb
<div id="micropost-<%= micropost.id  %>" >
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <div class="replace">
    <span class="content"><%= link_to micropost.content,micropost %>
      <%= image_tag micropost.picture.url if micropost.picture? %>
    </span>
  </div>
  <span class="timestamp">Asked by <%= link_to micropost.user.name, micropost.user %></span>
  <span class="timestamp">
    Posted <%= time_of_creation(micropost.created_at)%> .
    <% if current_user?(micropost.user) %>
    <%=  link_to "edit",edit_micropost_path(micropost), remote: true %>
    <%=  link_to "delete",micropost,method: :delete,data:{confirm: "are you sure?"} %>
    <% end %>
    <div class="submit-button">
    <span class="answer-button-<%= micropost.id %>"><div class="btn btn-primary">Respond</div></span>
    </div>

  </span>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages',object:f.object  %>
<div class="field">
  <%= f.text_area :content, placeholder: "Start a discussion..." %>
</div>
<span class="picture">
  <section class="buttons-post">
    <section  class="picture-tab">
      <%= f.file_field :picture,accept: 'image/jpeg,image/gif,image/png' %>
    </section>
    <section  class="post-button">
      <%= f.submit "Post", class: "btn btn-primary" %>
    </section>
  </section>
</span>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

<% end %>

app/views/shared/_stats.html.erb
<% @user ||=current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>