config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following,:followers
    end
  end
  resources :answers,only:[:new,:create,:edit,:update]
  resources :account_activations,only:[:edit]
  resources :password_resets,only:[:new,:create,:edit,:update]
  resources :microposts,only:[:edit,:create,:destroy,:update,:show,:more] do
    member do
      get :more
    end
  end
  resources :relationships,only: [:create,:destroy]
  root 'static_pages#home'
  get 'home',            to:      'static_pages#home'
  get 'help'  ,            to:     'static_pages#help'
  get 'about'                =>      'static_pages#about'
  get 'contact'              =>     'static_pages#contact'
  get 'signup'               =>    'users#new'
  get 'login',                 to:    'sessions#new'
  post 'login',                 to:     'sessions#create'
  delete 'logout',                to:    'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>

  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path%></li>
      <li><a href="https://www.facebook.com/rajeevriitm" target="_blank">Facebook</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <%= link_to "Settle It Now", root_path,id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",root_path%></li>
          <% if logged_in? %>
          <li><%= link_to "Users",users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
              Account <b class="carret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile Page", current_user %></li>
              <li><%= link_to "Settings",edit_user_path(current_user) %></li>
              <li class="divider"> </li>
              <li><%= link_to "Logout",logout_path, method: :delete %></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Login",login_path %></li>
          <%end%>
          <li><%= link_to "Help",help_path%></li>
          <% if logged_in? %>
          <li  class="search-form">
          <%= form_tag users_path,method: :get do %>
            <%= text_field_tag :search  %></li><li class="search">
            <%= submit_tag "Search"  %>
            <% end %></li>
            <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title_display(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
  <%= render "layouts/header.html.erb" %>
  <div class="container">
    <% flash.each do |message_type, message| %>
     <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer.html.erb" %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>